import { Text, TouchableOpacity, View } from "react-native";
import { s } from "../App.style";
import { finishGame } from "../utils/finishGame";

export function NewGameButton({
  setShowOutOfSpinsMessage,
  actorWordsRemovedAbove,
  setActorWordsRemovedAbove,
  verbWordsRemovedAbove,
  setVerbWordsRemovedAbove,
  wordMixRemovedAbove,
  setWordMixRemovedAbove,
  actorWordsRemovedBelow,
  setActorWordsRemovedBelow,
  verbWordsRemovedBelow,
  setVerbWordsRemovedBelow,
  wordMixRemovedBelow,
  setWordMixRemovedBelow,
  setShowCorrectSentenceDisplay,
  setShowPointsMessage,
  setRoundsLeft,
  roundsLeft,
  nudgesSpinsLeft,
  setNudgesSpinsLeft,
  cashButtonPressed,
  setCashButtonPressed,
  numberOfRows,
  fullWordArray,
  setFullWordArray,
  rowLength,
  verticalArrayActors,
  setVerticalArrayActors,
  verticalArrayVerbs,
  setVerticalArrayVerbs,
  verticalArrayWordMix,
  setVerticalArrayWordMix,
  showFinishGameMessage,
  setShowFinishGameMessage,
  gameScore,
  setGameScore,
  showNewGameButton,
  setShowNewGameButton,
  showCashButton,
  setShowCashButton,
                  wordArrayPopulated,
  setWordArrayPopulated,
    correctWords,
  setCorrectWords,
  arrayCorrectWords,
  setArrayCorrectWords
}) {
  return (
    <>
      <View style={s.newRoundContainer}>
        <TouchableOpacity
          style={s.newRoundButton}
          onPress={() =>
            finishGame(
              setShowOutOfSpinsMessage,
              actorWordsRemovedAbove,
              setActorWordsRemovedAbove,
              verbWordsRemovedAbove,
              setVerbWordsRemovedAbove,
              wordMixRemovedAbove,
              setWordMixRemovedAbove,
              actorWordsRemovedBelow,
              setActorWordsRemovedBelow,
              verbWordsRemovedBelow,
              setVerbWordsRemovedBelow,
              wordMixRemovedBelow,
              setWordMixRemovedBelow,
              setShowCorrectSentenceDisplay,
              setShowPointsMessage,
              setRoundsLeft,
              roundsLeft,
              nudgesSpinsLeft,
              setNudgesSpinsLeft,
              cashButtonPressed,
              setCashButtonPressed,
              numberOfRows,
              fullWordArray,
              setFullWordArray,
              rowLength,
              verticalArrayActors,
              setVerticalArrayActors,
              verticalArrayVerbs,
              setVerticalArrayVerbs,
              verticalArrayWordMix,
              setVerticalArrayWordMix,
              gameScore,
              setGameScore,
              showFinishGameMessage,
              setShowFinishGameMessage,
              setShowNewGameButton,
              showCashButton,
              setShowCashButton,
                wordArrayPopulated,
  setWordArrayPopulated,
    correctWords,
  setCorrectWords,
  arrayCorrectWords,
  setArrayCorrectWords
            )
          }
        >
          <Text style={s.word}>NEW GAME</Text>
        </TouchableOpacity>
      </View>
    </>
  );
}
