import { spinAndReset } from "./resetRound";

function finishGame(
              setShowOutOfSpinsMessage,
              actorWordsRemovedAbove,
              setActorWordsRemovedAbove,
              verbWordsRemovedAbove,
              setVerbWordsRemovedAbove,
              wordMixRemovedAbove,
              setWordMixRemovedAbove,
              actorWordsRemovedBelow,
              setActorWordsRemovedBelow,
              verbWordsRemovedBelow,
              setVerbWordsRemovedBelow,
              wordMixRemovedBelow,
              setWordMixRemovedBelow,
              setShowCorrectSentenceDisplay,
              setShowPointsMessage,
              setRoundsLeft,
              roundsLeft,
              nudgesSpinsLeft,
              setNudgesSpinsLeft,
              cashButtonPressed,
              setCashButtonPressed,
              numberOfRows,
              fullWordArray,
              setFullWordArray,
              rowLength,
              verticalArrayActors,
              setVerticalArrayActors,
              verticalArrayVerbs,
              setVerticalArrayVerbs,
              verticalArrayWordMix,
              setVerticalArrayWordMix,
              gameScore,
              setGameScore,
              showFinishGameMessage,
              setShowFinishGameMessage,
              setShowNewGameButton,
              showCashButton,
              setShowCashButton,
                wordArrayPopulated,
  setWordArrayPopulated,
    correctWords,
  setCorrectWords,
  arrayCorrectWords,
  setArrayCorrectWords

) {
  console.log("finish game button pressed!!!!!");
  spinAndReset(
  fullWordArray,
  setFullWordArray,
  rowLength,
  numberOfRows,
  cashButtonPressed,
  setCashButtonPressed,
  setShowCorrectSentenceDisplay,
  setShowPointsMessage,
  roundsLeft,
  setRoundsLeft,
  nudgesSpinsLeft,
  setNudgesSpinsLeft,
  setShowOutOfSpinsMessage,
  showFinishGameMessage,
  setShowFinishGameMessage,
  actorWordsRemovedAbove,
  setActorWordsRemovedAbove,
  verbWordsRemovedAbove,
  setVerbWordsRemovedAbove,
  wordMixRemovedAbove,
  setWordMixRemovedAbove,
  actorWordsRemovedBelow,
  setActorWordsRemovedBelow,
  verbWordsRemovedBelow,
  setVerbWordsRemovedBelow,
  wordMixRemovedBelow,
  setWordMixRemovedBelow,
  setShowNewGameButton,
  verticalArrayActors,
  setVerticalArrayActors,
  verticalArrayVerbs,
  setVerticalArrayVerbs,
  verticalArrayWordMix,
  setVerticalArrayWordMix,
  showCashButton,
  setShowCashButton,

  wordArrayPopulated,
  setWordArrayPopulated,
  correctWords,
  setCorrectWords,
  arrayCorrectWords,
  setArrayCorrectWords

  );
  setShowNewGameButton(false);
  setGameScore(0);
  setShowFinishGameMessage(false);
  setRoundsLeft(10);
}

export { finishGame };
