const wordList = ["A", "THE", "ALL", "IS", "ARE", "CAN", "CANNOT", "WILL", "WON'T", "LOVES", "LIKES", 
"I", "YOU", "WE", "THEY", "IT", "HARRY", "HANS", "TYRONE", "INGE", "CARLOS", "ALBERTO", "ANNA", "HIROKO", "PIERRE", "SUNITA", 
"SANJAY", "CHILDREN", "ADULTS", "EVERYONE", "NO ONE", "ALI", "MUSTAFA", "LeEILA", "LATOYA", "JOHN", "AGATHA", "MELANIE", "GERALD", "ROSA", "MARTIN",
"CAT", "DOG", "TREE", "CAR", "BOOK", "HOUSE", "RIVER", "MOUNTAIN", "GAME", "COMPUTER", "NEVER", "ALWAYS", "RUNS", "PAINTS", "JOKES",
"RUN", "JUMP", "EAT", "SLEEP", "WRITE", "READ", "DRIVE", "FLY", "SWIM", "THINK", "IS", "DOES", "DO", "LIKE", "LIKES", "WAS",
"HAPPY", "SAD", "BRIGHT", "DARK", "QUICK", "SLOW", "BLUE", "GREEN", "STRONG", "KIND",
"QUICKLY", "SLOWLY", "HAPPILY", "SADLY", "LOUDLY", "SILENTLY", "EAGERLY", "BOLDLY", "CALMLY", "NEATLY",
"I", "YOU", "HE", "SHE", "IT", "WE", "THEY", "ME", "HIM", "HER",
"TCAT", "TDOG", "RIVER", "BOOK", "HOUSE", "MOUNTAIN", "CAR", "GAME", "COMPUTER", "TREE",
"RUNS", "JUMPS", "EATS", "SLEEPS", "WRITES", "READS", "DRIVES", "FLIES", "SWIMS", "THINKS",
"HAPPY", "NOT", "QUICKLY", "SLOWLY", "BRIGHT", "NOT", "KIND", "STRONG", "HAPPY", "EXTREMELY",
"IN THE PARK", "ON", "UNDER", "BEFORE", "AFTER", "JOY", "WITHOUT ", " HOME", "BY", "IN",
"APPLE", "BANANA", "PENCIL", "NOTEBOOK", "PHONE", "WINDOW", "DOOR", "FLOOR", "SKY", "CLOUD",
"FAST", "JHIGH", "SLOWLY", "DEEPLY", "WNEATLY", "RQUIETLY", "SAFELY", "FLOW", "DRAWS", "HARD",
"SUN", "MOON", "STAR", "PLANET", "LIGHT", "SHADOW", "RAIN", "SNOW", "STORM", "WIND",
"LOUD", "QUIET", "HOT", "COLD", "WET", "DRY", "CLEAN", "DIRTY", "NEW", "OLD",
"LOOK", "SEE", "HEAR", "TOUCH", "SMELL", "TASTE", "HOLD", "THROW", "CATCH", "DROP",
"WALK", "CLIMB", "SIT", "STAND", "CRAWL", "RUN", "SKIP", "HOP", "DANCE", "SPIN",
"LAUGH", "CRY", "SMILE", "FROWN", "SHOUT", "WHISPER", "SING", "YELL", "TALK", "MUMBLE",
"CIRCLE", "SQUARE", "TRIANGLE", "RECTANGLE", "LINE", "DOT", "SHAPE", "COLOR", "PATTERN", "DESIGN",
"DAY", "NIGHT", "MORNING", "EVENING", "TODAY", "TOMORROW", "YESTERDAY", "WEEK", "MONTH", "YEAR",
"FIRST", "LAST", "NEXT", "THEN", "BEFORE", "AFTER", "ALWAYS", "NEVER", "SOMETIMES", "OFTEN",
"ABOVE", "BELOW", "INSIDE", "OUTSIDE", "NEAR", "FAR", "HERE", "THERE", "EVERYWHERE", "NOWHERE",
"YES", "NO", "MAYBE", "SURE", "OKAY", "ALRIGHT", "FINE", "GREAT", "COOL", "WOW", "RIVER", "ENERGY", "VISIT", "FAST", "VILLAGE", "LION", "VALUE", "EAGLE",
"HERO", "BRAVE", "PEACE", "IDEA", "OCEAN", "VILLAGE", "QUIET", "JOY", "ISLAND", "SMART", "DRIVE", "QUICK", "HOPE", "DANCE", "VALUE", "X-RAY", "READ", "HERO", "TIME", "ENERGY",
"HOUSE", "LEARN", "FRIEND", "VISIT", "LION", "ZEBRA", "BOLD", "SMART", "YEARN", "DANCE", "YOGURT", "ISLAND", "ANT", "UMBRELLA", "MIND", "YEARN",
"GREAT", "YEARN", "KEEP", "XENON", "OCEAN", "ZOOM", "PENCIL", "NOTEBOOK", "KING", "GREAT", "RUN", "JUMP", "XENON", "APPLE", "UMBRELLA", "ANT",
"VILLAGE", "FUN", "EFFORT", "FRIEND", "KIND", "UMBRELLA", "NOTEBOOK", "YOGURT", "TALK", "HOPE", "JOY", "VILLAGE", "TALK", "KIND",
"INSPIRE", "KIND", "ENERGY", "YOUNG", "JUNGLE", "YOGURT", "SMART", "KEEP", "WIN", "ANT", "VISIT", "JUMP", "UNDER", "USE", "DANCE",
"LION", "RUN", "YOGURT", "GIFT", "RUN", "XYLOPHONE", "CHAIR", "GREAT", "ZING", "YEARN", "LION", "NATURE", "INSPIRE", "ACTOR", "NATURE",
"MOUNTAIN", "FUN", "VILLAGE", "INSPIRE", "PENCIL", "GARDEN", "LOVE", "GIFT", "DRIVE", "FRIEND", "RIVER", "UNDER", "BANANA", "NICE",
"UNDER", "APPLE", "CLOUD", "ANT", "USE", "QUEEN", "DRIVE", "NOTEBOOK", "BRAVE", "XENON", "SUN", "QUIET", "KEEP", "ART", "WARM", "X-RAY", "DANCE", "JUMP",
"YEARN", "IDEA", "WINS", "YEARNS", "WIN", "KING", "ZEBRA", "QUEEN", "QUIET", "SUN", "DRIVING", "RUNNING", "HOPE", "TREE", "YOUNG", "LEARNT", "QUICK", "KING", "SUN",
"GARDEN", "DRIVE", "RUN", "PENCIL", "KING", "QUICK", "UMBRELLA", "ART", "GREAT", "BRIGHT", "MIND", "ZEBRA", "EAGLE", "RIVER", "UNDER", "SMILE", "VISIT",
"BANANA", "FAST", "MOUNTAIN", "OPEN", "JOY", "NICE", "USE", "PEACE", "CHAIR", "GARDEN", "FAST", "MUSIC", "HOUSE", "OPEN", "DRIVE", "FRIEND", "GIFT", "YOUNG", "CHAIR", "FUN",
"VISIT", "JUNGLE", "ZEBRA", "BRIGHT", "PLAY", "SUN", "OPEN", "PEACE", "GREAT", "PLAY", "NOTEBOOK", "CHAIR", "OPEN", "INSPIRE", "SMART", "YOGURT", "NICE", "MOUNTAIN",
"FRIEND", "HOUSE", "NOTEBOOK", "PENCIL", "XENON", "XENON", "UNDER", "SMART", "IDEA", "CALM", "BRAVE", "HOUSE", "SMART", "ANT", "BANANA", "WARM", "ZOOM", "LOVE", "KIND",
"CLOUD", "RIVER", "RUN", "WARM", "EFFORT", "MOUNTAIN", "NATURE", "HOPE", "ISLAND", "PEACE", "OCEAN", "NOTEBOOK", "ACTOR", "ENERGY", "YOUNG", "OPEN", "ANT", "ORGANIZE",
"FAST", "XENON", "JUNGLE", "RIVER", "ZOOM", "ENERGY", "MIND", "ENERGY", "BOLD", "FUN", "XYLOPHONE", "APPLE", "UNDER", "EAGLE", "USE", "FUN", "TREE", "TALK", "NATURE", "QUEEN",
"ORGANIZE", "XENON", "APPLE", "EFFORT", "ACTOR", "WINDOW", "SMILE", "DRIVE", "EFFORT", "ART", "DREAM", "MOUNTAIN", "MUSIC", "XYLOPHONE", "GIFT", "USE", "TREE", "SMART",
"NATURE", "USE", "KIND", "LION", "PEACE", "DRIVE", "EAGLE", "MOUNTAIN", "FAST", "RUN", "WIN", "ACTOR", "BOLD", "YOUNG", "TIME", "HOUSE", "OPEN", "OCEAN", "ISLAND", "LOVE", "ART",
"UMBRELLA", "TREE", "MUSIC", "WINDOW", "UNDER", "LEARN", "INSPIRE", "JUNGLE", "WINDOW", "MOUNTAIN", "QUEEN", "USE", "BRIGHT", "BRAVE", "QUICK", "TREE", "ISLAND", "FRIEND", "APPLE",
"RUN", "BANANA", "ART", "READ", "BRAVE", "MOUNTAIN", "GREAT", "YOGURT", "LION", "HERO", "VALUE", "WINDOW", "JUMP", "QUIET", "CALM", "NATURE", "KEEP", "MUSIC", "JUMP", "X-RAY",
"NOTEBOOK", "CLOUD", "ORGANIZE", "HERO", "ENERGY", "LEARN", "PENCIL", "LION", "CLOUD", "TIME", "TIME", "INSPIRE", "QUICK", "DRIVE", "OCEAN", "GARDEN", "VILLAGE", "QUEEN",
"BANANA","MIND","WARM","JUNGLE","ORGANIZE","MUSIC","FRIEND","VALUE","UNDER","GREAT","KEEP","KIND","ISLAND","BANANA","READ","ACTOR","BRIGHT","APPLE","FUN","JUNGLE",
"BRIGHT","READ","GARDEN","BANANA","PLAY","LOVE","GREAT","CALM","DANCE","QUIET","VALUE","QUICK","WIN","BRAVE","PEACE","QUICK","SUN","EFFORT","PLAY","SMILE",
"VILLAGE","LOVE","BANANA","GIFT","BANANA","QUIET","YOUNG","KEEP","CLOUD","BOLD","JOY","GARDEN","EFFORT","SMILE","LEARN","JUMP","BOLD","READ","APPLE","MUSIC",
"GREAT","WIN","YEARN","PENCIL","YOGURT","LOVE","JOY","TREE","ART","UMBRELLA","DANCE","ISLAND","ZOOM","BOLD","XENON","MUSIC","EFFORT","TIME","HERO","SUN","ZEBRAS",
"OPEN","X-RAY","JUMP","FRIEND","X-RAY","FUN","JOY","X-RAY","SUN","ACTOR","ACTOR","NICE","IDEA","TALK","TREE","BRIGHT","ISLAND","NICE","HOUSE","ZEBRA",
"VALUE","X-RAY","PLAY","RUN","MUSIC","CHAIR","QUIET","READ","OPEN","HERO","WARM","GREAT","READ","CLOUD","SMILE","ZOOM","OPEN","DRIVE","HERO","EFFORT","TIME",
"BOLD","MOUNTAIN","JOY","EFFORT","PLAY","ZING","RIVER","NOTEBOOK","VILLAGE","INSPIRE","NICE","OCEAN","EAGLE","DANCE","ZOOM","BOLD","GIFT","TALK","DREAM",
"CHAIR","BRIGHT","LEARN","LOVE","LOVE","KING","FUN","SMILE","SUN","IDEA","WINDOW","YOUNG","X-RAY","DREAM","XENON","TIME","DREAM","JOY","LEARN","SMILE",
"PEACE","ANT","PEACE","QUEEN","PENCIL","SMILE","ZING","KEEP","BRIGHT","TALK","OCEAN","EAGLE","ZEBRA","TIME","ORGANIZE","NATURE","CLOUD","CALM","HERO",
"EAGLE","ZEBRA","INSPIRE","KING","VISIT","CALM","WARM","LEARN","WIN","OCEAN","HOPE","WARM","JUNGLE","EAGLE","FAST","ART","WARM","ORGANIZE","YEARN","RIVER",
"ZING","YOUNG","TALK","CLOUD","GIFT","RIVER","KING","MIND","QUICK","ENERGY","ZOOM","HERO","WIN","BOLD","QUICK","NATURE","KIND","VISIT","ENERGY","USE","ZOOM",
"DANCE","GIFT","HOPE","NICE","QUIET","ZING","ART","ISLAND","JUNGLE","NOTEBOOK","XYLOPHONE","INSPIRE","EAGLE","XYLOPHONE","MIND","KING","INSPIRE","TALK","MIND",
"UNDER","CHAIR","JOY","IDEA","VALUE","MUSIC","BRAVE","FAST","SUN","XYLOPHONE","ART","UMBRELLA","WINDOW","GARDEN","ART","HERO","SMILE","KING","DREAM","WINDOW",
"ORGANIZE","QUEEN","JUMP","PLAY","FRIEND","DANCE","ZING","QUEEN","YEARN","BRAVE","CALM","VISIT","DREAM","ZING","VALUE","NOTEBOOK","TIME","CLOUD","BRAVE","MIND",
"ZING","PLAY","UMBRELLA","XENON","ORGANIZE","CALM","TREE","IDEA","XYLOPHONE","LEARN","HOUSE","KEEP","VILLAGE","XYLOPHONE","YOUNG","PENCIL","IDEA","NICE","HOUSE",
"X-RAY","NOTEBOOK","ACTOR","DRIVE","FAST","WARM","GREAT","WINDOW","VISIT","WINDOW","YOGURT","ZOOM","ANT","CHAIR","READ","ANT","DREAM",
"LION","KIND","X-RAY","DREAM","HOPED","TREE","SMART","CALM","APPLE","EFFORT","KEEP","NICE","HOPE","BRIGHT","READ","LEARN","CALM","DANCE","GARDEN","EAGLE","CALM"
,"SPAIN", "SYRIA", "GERMAN", "LATVIA", "SWEDISH"

  ];

  const list1=["I", "I","I", "I", "I","I", "I", "YOU", "YOU","YOU", "YOU","YOU", "YOU","WE", "WE","WE", "WE","WE","WE", "WE","THEY", "THEY","THEY", "THEY", 
    "IT", "IT", "IT", "IT", "HE", "HE", "HE", "HE", "HE", "HE","HE", "SHE", "SHE", "SHE", "SHE", "SHE", "SHE", "SHE", "SHE",  "HARRY", "HANS", "TYRONE", "INGE", 
    "CARLOS", "ALBERTO", "ANNA", "HIROKO", "PIERRE", "SUNITA", 
    "SANJAY", "CHILDREN", "ADULTS", "EVERYONE", "NO ONE", "ALI", "MUSTAFA", "LILA", "LATOYA", "JOHN", "AGATHA", "MELANIE", "GERALD", "ROSA", "MARTIN",
    "PEOPLE", "CATS", "ELEPHANTS", "DETECTIVES", "PATRICK", "JOSE", "LUCIANA", "MATT", "KEISHA", "SARA", 
  ]
  const verbList=["RUN", "RAN", "RUNNING", "JUMP", "JUMPED", "JUMPPS", "IS", "IS", "IS", "IS", "IS", "IS", "ARE",  "ARE", "ARE",  "ARE", "AM", "HAS", "HAS"
,"HAS", "HAS", "HAS", "HAS", "EAT", "ATE", "EATING", "SLEEPS", "SLEPT", "SLEEPING",
"WRITE", "WROTE", "WRITES", "READ", "READING", "READS",
"DRIVE", "DROVE", "DRIVING", "FLY", "FLEW", "FLYING", "FLIES",
"SWIM",  "SWIMS","SWAM", "SWIMMING", "THINK", "THOUGHT", "THINKS",
"GO", "WENT", "GOING", "COME", "CAME", "COMES",
"MAKE", "MADE", "MAKING", "TAKE", "TOOK", "TAKES",
"SEE", "SAWS",  "HEAR", "HEARD", "HEARS",
"FEEL", "FEELS", "FEELING", "SPEAK", "SPOKE", "SPEAKS",
"BUY", "BOUGHT", "BUYS", "SELL", "SOLD", "SELLS",
"TEACH", "TAUGHT", "TEACHES", "LEARN", "LEARNS", "LEARNING",
"PLAY", "PLAYED", "PLAYS", "WORK", "WORKED", "WORKS",
"CALL", "CALLED", "CALLING", "OPEN", "OPENED", "OPENS",
"CLOSE", "CLOSES", "CLOSING", "START", "STARTED", "STARTS",
"FINISH", "FINISHED", "FINISHES", "BUILD", "BUILDS", "BUILDING",
"BREAK", "BROKE", "BREAKS", "CLEAN", "CLEANED", "CLEANS",
"COOK", "COOKS", "COOKING", "WATCH", "WATCHED", "WATCHES",
"LISTEN", "LISTENS", "LISTENING", "WALK", "WALKED", "WALKING",
"SIT", "SAT", "SITTING", "STAND", "STANDS", "STANDING",
"THROW", "THREW", "THROWING", "CATCH", "CAUGHT", "CATCHIES",
"CLIMB", "CLIMBED", "CLIMBS", "DRAW", "DRAWS", "DRAWING",
"PAINT", "PAINTED", "PAINTING", "DANCE", "DANCED", "DANCES",
"SING", "SINGS", "SINGING", "SMILE", "SMILED", "SMILING",
"LAUGH", "LAUGHED", "LAUGHS", "CRY", "CRIED", "CRIES",
"SHOUT", "SHOUTED", "SHOUTING", "WHISPER", "WHISPERS", "WHISPERING",
"HELP", "HELPED", "HELPS", "HUG", "HUGS", "HUGGING",
"KISS", "KISSED", "KISSES", "WAIT", "WAITED", "WAITING",
"LOVE", "LOVED", "LOVES", "HATE", "HATED", "HATES", 
"AM", "ARE", "IS", "CAN", "COULD", "CRAWLS"
  ]

  const list2=["EAT", "EATS", "GO", "GOES", "LIKE", "LIKES"
      ]
  const beingVerbList=[
    "AM", "ARE", "IS"
  ]
  const adverbList=[
    "QUICKLY", "SLOWLY", "HAPPILY", "SADLY", "ANGRILY", "EAGERLY", "LOUDLY", "SOFTLY", "NEATLY", "MESSILY",
"BRAVELY", "CAREFULLY", "CARELESSLY", "CHEERFULLY", "DAILY", "WEEKLY", "MONTHLY", "YEARLY", "EASILY", "BARELY",
"NEVER", "ALWAYS", "OFTEN", "RARELY", "SOMETIMES", "USUALLY", "SELDOM", "NOW", "THEN", "LATER",
"BEFORE", "AFTER", "ABOVE", "BELOW", "TOGETHER", "APART", "FORWARD", "BACKWARD", "INSIDE", "OUTSIDE",
"EARLY", "LATE", "HERE", "THERE", "EVERYWHERE", "ANYWHERE", "SOMEWHERE", "NOWHERE", "UP", "DOWN",
"NEARBY", "AHEAD", "BEHIND", "SIDEWAYS", "UPSTAIRS", "DOWNSTAIRS", "TODAY", "TOMORROW", "YESTERDAY", "RECENTLY",
"ALMOST", "QUITE", "RATHER", "TOO", "VERY", "EXTREMELY", "ABSOLUTELY", "COMPLETELY", "TOTALLY", "BARELY",
"GRADUALLY", "SUDDENLY", "SHARPLY", "DEEPLY", "GENTLY", "CALMLY", "NATURALLY", "HONESTLY", "TRUTHFULLY", "SIMPLY",
"FRANKLY", "SERIOUSLY", "LOOSELY", "TIGHTLY", "BOLDLY", "POLITELY", "RUDELY", "BRIGHTLY", "DIMLY", "WILLINGLY",
"UNWILLINGLY", "CERTAINLY", "PROBABLY", "POSSIBLY", "DOUBTFULLY", "NEEDLESSLY", "WORRIEDLY", "HOPEFULLY", "THANKFULLY", "THOUGHTFULLY"


  ]
  const wordMix=["CHICKEN", "SALAD", "CAKE", "BURGERS", "CARROTS", "SWEETS", "FISHING", "SWIMMING", "WALKING", "OUT", "AWAY", "SKIING", "READING",
    "GAMES", "CATS", "FOOTBALL", "SLOWLY"


  ]

  const gerundList=[
    "ACTING","ADDING","ADMIRING","ADVISING","ANALYZING","ANSWERING","APPRECIATING","ARGUING","ARRANGING","ASKING","ASSEMBLING","ASSISTING","ASSUMING","ATTACKING",
    "ATTEMPTING","AVOIDING","BAKING","BALANCING","BATHING","BEHAVING","BELIEVING","BLAMING","BLEEDING","BLOWING","BOASTING","BORROWING","BREAKING","BRINGING",
    "BUILDING","BURNING","BUYING","CALLING","CARING","CARRYING","CHANGING","CHEATING","CHOKING","CHOOSING","CLAPPING","CLEANING","CLIMBING","CLOSING","COOKING",
    "COPYING","CORRECTING","COUGHING","COVERING","CREATING","CRYING","CUTTING","DANCING","DECIDING","DESCRIBING","DESIGNING","DESTROYING","DISCUSSING","DISLIKING",
    "DIVING","DOING","DRAWING","DRINKING","DRIVING","DUSTING","EATING","ENJOYING","EXERCISING","EXPLAINING","FALLING","FEEDING","FEELING","FIGHTING","FIXING",
    "FLYING","FOLLOWING","FORGETTING","FORGIVING","FREEZING","GATHERING","GIVING","GOING","GRABBING","GUESSING","HANGING","HAVING","HEARING","HELPING","HIDING",
    "HITTING","HOLDING","HOPING","HUGGING","HURTING","IMAGINING","IMPROVING","INCREASING","INVENTING","INVITING","JOGGING","JUMPING","KEEPING","KICKING","KILLING",
    "KISSING","KNOWING","LAUGHING","LEARNING","LEAVING","LENDING","LETTING","LICKING","LIFTING","LIKING","LISTENING","LIVING","LOOKING","LOSING","LOVING","MAKING",
    "MANAGING","MEETING","MISSING","MOVING"

  ]



export { adverbList, beingVerbList, gerundList, list1, list2, verbList, wordList, wordMix };

